name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql-service:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      APP_URL: "http://127.0.0.1:8000"
      CI: true
      DB_CONNECTION: mysql
      DB_DATABASE: testing
      DB_HOST: 127.0.0.1
      DB_PASSWORD: password
      DB_PORT: 33306
      DB_USERNAME: root

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Laravel
        run: composer create-project laravel/laravel example-app

      - name: Unpack Boilerplate
        run: |
          mkdir ./example-app/e2e
          mv ./src/Controllers/* ./example-app/app/Http/Controllers
          mv ./src/routes/* ./example-app/routes
          mv ./src/stubs/laravel-examples.spec.ts ./example-app/e2e/laravel-examples.spec.ts
          mv ./src/stubs/laravel-helpers.ts ./example-app/e2e/laravel-helpers.ts
          mv ./src/stubs/playwright.config.ts ./example-app/playwright.config.ts

      - name: Install Playwright
        run: |
          cd example-app
          npm init playwright -- --quiet --install-deps --gha --browser chromium
          npm install dotenv
          npm install @playwright/test

      - name: Setup Package
        run: |
          cd example-app
          mv composer.json composer.old.json
          node -p "JSON.stringify({ ...require('./composer.old.json'), repositories: [{ type: 'path', url: '../' }] }, null, 2)" > composer.json
          composer require "web-id/laravel-playwright @dev"
          cat composer.json

      # - name: Create Boilerplate
      #   run: |
      #     cd example-app
      #     php artisan playwright:boilerplate

      - name: Run Migrations
        run: |
          cd example-app
          php artisan migrate:fresh

      - name: Unit & Feature tests
        run: |
          cd example-app
          php artisan test

      - name: Playwright tests
        run: |
          cd example-app
          php artisan serve > /dev/null 2>&1 &
          npx playwright test
          